blueprint:
  name: Humidity Management
  description: Turn a fan on and off based on the difference between humidity sensors and a baseline
  domain: automation
  input:
    humidity_sensor_bathroom1:
      name: Humidity Sensor for Bathroom 1
      description: A sensor that measures the humidity of the first bathroom
      selector:
        entity:
          domain: sensor
          multiple: false
    humidity_sensor_bathroom2:
      name: Humidity Sensor for Bathroom 2
      description: A sensor that measures the humidity of the second bathroom
      selector:
        entity:
          domain: sensor
          multiple: false
    reference_humidity:
      name: Reference Humidity
      description: A percentage point value that indicates the baseline humidity if there is no reference sensor available
      default: 60
    reference_humidity_sensor:
      name: Reference Humidity Sensor
      description: A sensor that indicates the baseline humidity of the location
      selector:
        entity:
          domain: sensor
          multiple: false
      default: []
    fan_switch:
      name: Fan Switch
      description: A switch that turns the fan on and off
      selector:
        entity:
          domain: switch
          multiple: false
    rising_threshold:
      name: Rising Threshold
      description: How many percentage points above the reference humidity the sensor can rise before the fan is turned on
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider
      default: 8
    falling_threshold:
      name: Falling Threshold
      description: How many percentage points above the reference humidity the sensor must fall to before the fan is turned off
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider
      default: 3
  source_url: 
trigger:
- platform: state
  entity_id: !input humidity_sensor_bathroom1
- platform: state
  entity_id: !input humidity_sensor_bathroom2
- platform: state
  entity_id: !input reference_humidity_sensor
condition:
- condition: template
  value_template: '{{ mode != switch_state }}'
action:
- service: switch.turn_{{mode}}
  entity_id: !input fan_switch
variables:
  reference_humidity: !input reference_humidity
  humidity_sensor_bathroom1: !input humidity_sensor_bathroom1
  humidity_sensor_bathroom2: !input humidity_sensor_bathroom2
  reference_humidity_sensor: !input reference_humidity_sensor
  fan_switch: !input fan_switch
  switch_state: '{{ states(fan_switch) }}'
  rising_threshold: !input rising_threshold
  falling_threshold: !input falling_threshold
  difference_bathroom1: '{{ states(humidity_sensor_bathroom1)|float - (states(reference_humidity_sensor)|float or reference_humidity|float) }}'
  difference_bathroom2: '{{ states(humidity_sensor_bathroom2)|float - (states(reference_humidity_sensor)|float or reference_humidity|float) }}'
  mode: '{% set differences = [difference_bathroom1|float, difference_bathroom2|float] %}
